definitions:
  main.createLobbyRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  main.member:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /lobbies:
    post:
      consumes:
      - application/json
      description: create a new lobby with the given name
      parameters:
      - description: Create Lobby
        in: body
        name: lobby
        required: true
        schema:
          $ref: '#/definitions/main.createLobbyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new lobby
      tags:
      - lobbies
  /members:
    get:
      consumes:
      - application/json
      description: get a list of members
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.member'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List of members
      tags:
      - members
swagger: "2.0"
